spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
    password: 1234


  thymeleaf:
    cache: false

  jpa:
    hibernate:
      ddl-auto: create-drop

server:
  port: 80